application: beauty-bar
version: 4
runtime: python
api_version: 1

handlers:

- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /svgweb
  static_dir: static/svgweb

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /.*
  script: beautybar.py

