application: beauty-bar
version: 12
runtime: python
api_version: 1

handlers:

- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /svgweb
  static_dir: static/svgweb

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /beauty-bar.sh
  static_files: static/beauty-bar.sh
  upload: static/beauty-bar.sh

- url: /google156fd9a022590d56.html
  static_files: static/google156fd9a022590d56.html
  upload: static/google156fd9a022590d56.html

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /spreadsheet-gadget.xml
  static_files: static/spreadsheet-gadget.xml
  upload: static/spreadsheet-gadget.xml

- url: /stats.*
  script: appstats/ui.py

- url: /admin/.*
  script: beautybar.py
  login: admin

- url: /.*
  script: beautybar.py

