application: beauty-bar
version: 3
runtime: python
api_version: 1

handlers:

- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /svgweb
  static_dir: static/svgweb

- url: /.*
  script: beautybar.py

